In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load data from your CSV file (replace '[your_file].csv' with your actual file path in your project)
df = pd.read_csv("Final Dataset Assignment 2.csv")
df

,Gender,Age,Height,Weight,family_history_with_overweight,Consumption of Vegetables (FCVC),Number of Main Meals (NCP),Physical Activity Frequency (FAF),Smoker (SMOKE),Consumption of Alcohol (CALC),NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,2,3,0,no,no,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,3,3,3,yes,Sometimes,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,2,3,2,no,Frequently,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,3,3,2,no,Frequently,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,2,1,0,no,Sometimes,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...
2105,Female,20.976842,1.710730,131.408528,yes,3,3,2,no,Sometimes,Obesity_Type_III
2106,Female,21.982942,1.748584,133.742943,yes,3,3,1,no,Sometimes,Obesity_Type_III
2107,Female,22.524036,1.752206,133.689352,yes,3,3,1,no,Sometimes,Obesity_Type_III
2108,Female,24.361936,1.739450,133.346641,yes,3,3,1,no,Sometimes,Obesity_Type_III
2109,Female,23.664709,1.738836,133.472641,yes,3,3,1,no,Sometimes,Obesity_Type_III

In [3]:
# Calculate descriptive statistics
descriptive_stats = df.describe()
descriptive_stats

,Age,Height,Weight,Consumption of Vegetables (FCVC),Number of Main Meals (NCP),Physical Activity Frequency (FAF)
count,2110.000000,2110.000000,2110.000000,2110.000000,2110.000000,2110.000000
mean,24.311800,1.701607,86.577331,2.423223,2.687678,1.006161
std,6.347366,0.093271,26.194310,0.583909,0.809843,0.895413
min,14.000000,1.450000,39.000000,1.000000,1.000000,0.000000
25%,19.946718,1.630000,65.448643,2.000000,3.000000,0.000000
50%,22.774751,1.700357,83.000000,2.000000,3.000000,1.000000
75%,26.000000,1.768385,107.456672,3.000000,3.000000,2.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000

In [4]:
# Add additional statistics as I have mentioned during lectures, skewness, etc are important
descriptive_stats.loc['variance'] = df.var()
descriptive_stats.loc['skewness'] = df.skew()
descriptive_stats.loc['kurtosis'] = df.kurtosis()
descriptive_stats.loc['median'] = df.median()
# Display the descriptive statistics here in python
print(descriptive_stats)

                  Age       Height       Weight  \
count     2110.000000  2110.000000  2110.000000
mean        24.311800     1.701607    86.577331
std          6.347366     0.093271    26.194310
min         14.000000     1.450000    39.000000
25%         19.946718     1.630000    65.448643
50%         22.774751     1.700357    83.000000
75%         26.000000     1.768385   107.456672
max         61.000000     1.980000   173.000000
variance    40.289058     0.008699   686.141889
skewness     1.529185    -0.012520     0.256275
kurtosis     2.824792    -0.561329    -0.699684
median      22.774751     1.700357    83.000000

          Consumption of Vegetables (FCVC)  Number of Main Meals (NCP)  \
count                          2110.000000                 2110.000000
mean                              2.423223                    2.687678
std                               0.583909                    0.809843
min                               1.000000                    1.000000
25%                               2.000000                    3.000000
50%                               2.000000                    3.000000
75%                               3.000000                    3.000000
max                               3.000000                    4.000000
variance                          0.340949                    0.655846
skewness                         -0.428929                   -1.067579
kurtosis                         -0.709020                    0.377237
median                            2.000000                    3.000000

          Physical Activity Frequency (FAF)
count                           2110.000000
mean                               1.006161
std                                0.895413
min                                0.000000
25%                                0.000000
50%                                1.000000
75%                                2.000000
max                                3.000000
variance                           0.801764
skewness                           0.459956
kurtosis                          -0.710061
median                             1.000000

C:\Users\HP\AppData\Local\Temp\ipykernel_18436\332032020.py:2: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  descriptive_stats.loc['variance'] = df.var()
C:\Users\HP\AppData\Local\Temp\ipykernel_18436\332032020.py:3: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  descriptive_stats.loc['skewness'] = df.skew()
C:\Users\HP\AppData\Local\Temp\ipykernel_18436\332032020.py:4: FutureWarning: The default value of numeric_only in DataFrame.kurt is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  descriptive_stats.loc['kurtosis'] = df.kurtosis()
C:\Users\HP\AppData\Local\Temp\ipykernel_18436\332032020.py:5: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  descriptive_stats.loc['median'] = df.median()

In [7]:
!pip install openpyxl

# Save the descriptive statistics to an Excel file so you can  easily use it and format it for your individual report
descriptive_stats.to_excel('Python_assignment2_descriptive_stats.xlsx')

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     -------------------------------------- 250.9/250.9 kB 3.9 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [ ]:
# Save the descriptive statistics to an Excel file so you can  easily use it and format it for your individual report
descriptive_stats.to_excel('Python_assignment2_descriptive_stats.xlsx')